apiVersion: apps/v1 
kind: Deployment
metadata:
  name: test-swoft-server
  labels:
    server: test-swoft
spec:
  selector:
    matchLabels:
      server: test-swoft
  replicas: 1
  template: 
    metadata:
      labels:
        server: test-swoft
    spec:
      containers:
      - name: test-swoft-server
        image: registry.cn-shenzhen.aliyuncs.com/shenj/swoft_server:1.5
        ports:
        - containerPort: 18306
        - containerPort: 18307
        env:
        - name: dockerip
          value: 127.0.0.2
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: test-swoft-server
  labels:
    server: test-swoft
spec:
  selector:
    server: test-swoft
  type: NodePort
  # clusterIP: 10.106.100.2
  ports:
  - name: http
    protocol: TCP
    nodePort: 31000
    port: 18306
    targetPort: 18306
  - name: rpc
    protocol: TCP
    nodePort: 31001
    port: 18307
    targetPort: 18307